### PR TITLE
assets: branding rework

### LINKED ISSUE #14: Splash image and icon
Some graphical assets can be created / redone / chosen.

- [ ] homescreen icon
- [ ] homescreen icon background color
- [ ] splash screen image
- [ ] browser panel header background image?
- [ ] readme header image / screenshots

### PR DESCRIPTION
**Pull request by Informatic**
Closes #14 

New homescreen icon:
capture2
capture3

Splashscreen:
splash

Icon background color is the same as enyo/moonstone accent.

Up for comments.

### CODE REVIEW

**Comment by Informatic** [comment]
Alt, a little bowed maybe? Seems a little more fitting to other homescreen icons maybe? Not sure.
splash
icon160

**Comment by dfgg12** [comment]
Taking into consideration Korean origin of this software I'd like to propose to call it **Kimchi Channel**

**Comment by mariotaku** [comment]
> Taking into consideration Korean origin of this software I'd like to propose to call it **Kimchi Channel**

[_Soju_](https://en.wikipedia.org/wiki/Soju) channel lol

I must say this design & color scheme looks amazing to me!

**Comment by Informatic** [comment]
Updated original preview image in homescreen.

Rounded background with margins leads to some rendering artifacts around the edges on homescreen - most other icons have either fully transparent background, or fully opaque one (matching icon background color). I think, at least for https://repo.webosbrew.org rendering we should have an icon with background. Main repo now references 160x160 icon, while package/`appinfo.json` only uses 130 and 80 sizes. We can either have all icons the same main color background, or have 160 icon only have a background (with rounded corners there, since we won't have the artifacts)

**Comment by Informatic** [comment]
Final revision, I think it looks decent. Ended up putting a flat colored background on all icons.

capture

**Comment by Informatic** [comment]
I've fixed logo offset as per last comment, merging.

**Pull request merged**
