### PR TITLE
Register activity to call /autostart on boot

### PR DESCRIPTION
**Pull request by kitsuned**

### CODE REVIEW

**Comment by mariotaku** [comment]
Hey @kitsuned ! I have made some changes to the workflows, if you back-merge from main, it should fix the pipeline issue.

**Comment by kitsuned** [comment]
hi @mariotaku! done, i've rebased the branch.

**Comment by kitsuned** [comment]
oh! it looks like npm didn't like lockfile v2. let me drop the commit.

**Comment by mariotaku** [comment]
Sorry about the mess, I have recreated package-lock.json and it should be fine this time.

**Comment by kitsuned** [comment]
rebased :)

**Comment by mariotaku** [comment]
Great. Let me know if you need review & merge.

**Comment by kitsuned** [comment]
atm i'm looking for people with ancient devices (webOS 1-3).

i'll remove draft status as soon as I finish testing.

**Comment by kitsuned** [comment]
confirmed to be working properly on webOS 3.9, 4.4, 4.9 & 7.3.

**Comment by Chaoscontrol** [comment]
Would this fix SSH autostart on 3.4.0 too? 
I'm looking like mad for a way to make it start without needing to launch hb channel.

**Pull request merged**
