### PR TITLE
Add myself to FUNDING.yml and prepare for 0.7.0 release

### PR DESCRIPTION
**Pull request by throwaway96**

### CODE REVIEW

**Review by mariotaku — APPROVED** [review]

**Review by kitsuned — CHANGES_REQUESTED** [review]
#143 🥺

**Comment by throwaway96** [comment]
@kitsuned

Didn't that land in 0.6.0?

**Comment by kitsuned** [comment]
> @kitsuned
> 
> Didn't that land in 0.6.0?

not yet.

**Comment by throwaway96** [comment]
Oops! I missed a bunch of stuff, actually...

**Review by kitsuned — APPROVED** [review]

**Review by boomer14895 — COMMENTED** [review]
No Clue! I have obtained root access to tv but WebOS Device Manger desktop will not longer connect. I lost root once already due to this issue. I attempted to use developer mode but that's said to be a no no with successfully rooted device. I learned why the hard way when I lost root use privliages.

**Comment by mariotaku** [comment]
@boomer14895 If you have questions or need help with homebrew channel, or dev-manager-desktop, please create an issue in those repos so we can properly track and respond.

**Pull request merged**
